package org.xiwc.tool.entity.security;
// default package
// Generated May 6, 2015 5:07:53 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AclClass generated by hbm2java
 */
@Entity
@Table(name = "acl_class", uniqueConstraints = @UniqueConstraint(columnNames = "class"))
public class AclClass implements java.io.Serializable {

	/** serialVersionUID long */
	private static final long serialVersionUID = 2898078851828420098L;
	private Long id;
	private String class_;
	private Set<AclObjectIdentity> aclObjectIdentities = new HashSet<AclObjectIdentity>(0);

	public AclClass() {
	}

	public AclClass(String class_) {
		this.class_ = class_;
	}

	public AclClass(String class_, Set<AclObjectIdentity> aclObjectIdentities) {
		this.class_ = class_;
		this.aclObjectIdentities = aclObjectIdentities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "class", unique = true, nullable = false, length = 100)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aclClass")
	public Set<AclObjectIdentity> getAclObjectIdentities() {
		return this.aclObjectIdentities;
	}

	public void setAclObjectIdentities(Set<AclObjectIdentity> aclObjectIdentities) {
		this.aclObjectIdentities = aclObjectIdentities;
	}

}
