package org.xiwc.tool.entity.security;
// default package
// Generated May 6, 2015 5:07:53 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AclSid generated by hbm2java
 */
@Entity
@Table(name = "acl_sid", uniqueConstraints = @UniqueConstraint(columnNames = { "sid", "principal" }))
public class AclSid implements java.io.Serializable {

	/** serialVersionUID long */
	private static final long serialVersionUID = 3794251741478470037L;
	private Long id;
	private boolean principal;
	private String sid;
	private Set<AclObjectIdentity> aclObjectIdentities = new HashSet<AclObjectIdentity>(0);
	private Set<AclEntry> aclEntries = new HashSet<AclEntry>(0);

	public AclSid() {
	}

	public AclSid(boolean principal, String sid) {
		this.principal = principal;
		this.sid = sid;
	}

	public AclSid(boolean principal, String sid, Set<AclObjectIdentity> aclObjectIdentities, Set<AclEntry> aclEntries) {
		this.principal = principal;
		this.sid = sid;
		this.aclObjectIdentities = aclObjectIdentities;
		this.aclEntries = aclEntries;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "principal", nullable = false)
	public boolean isPrincipal() {
		return this.principal;
	}

	public void setPrincipal(boolean principal) {
		this.principal = principal;
	}

	@Column(name = "sid", nullable = false, length = 100)
	public String getSid() {
		return this.sid;
	}

	public void setSid(String sid) {
		this.sid = sid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aclSid")
	public Set<AclObjectIdentity> getAclObjectIdentities() {
		return this.aclObjectIdentities;
	}

	public void setAclObjectIdentities(Set<AclObjectIdentity> aclObjectIdentities) {
		this.aclObjectIdentities = aclObjectIdentities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aclSid")
	public Set<AclEntry> getAclEntries() {
		return this.aclEntries;
	}

	public void setAclEntries(Set<AclEntry> aclEntries) {
		this.aclEntries = aclEntries;
	}

}
