package org.xiwc.tool.entity.security;
// default package
// Generated May 6, 2015 11:39:38 AM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Group generated by hbm2java
 */
@Entity
@Table(name = "groups")
public class Group implements java.io.Serializable {

	/** serialVersionUID long */
	private static final long serialVersionUID = 3805010763422813183L;
	private Long id;
	private String groupName;
	private Set<GroupMember> groupMembers = new HashSet<GroupMember>(0);
	private Set<GroupAuthority> groupAuthorities = new HashSet<GroupAuthority>(0);

	public Group() {
	}

	public Group(String groupName) {
		this.groupName = groupName;
	}

	public Group(String groupName, Set<GroupMember> groupMembers, Set<GroupAuthority> groupAuthorities) {
		this.groupName = groupName;
		this.groupMembers = groupMembers;
		this.groupAuthorities = groupAuthorities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "group_name", nullable = false, length = 50)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "group")
	public Set<GroupMember> getGroupMembers() {
		return this.groupMembers;
	}

	public void setGroupMembers(Set<GroupMember> groupMembers) {
		this.groupMembers = groupMembers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "group")
	public Set<GroupAuthority> getGroupAuthorities() {
		return this.groupAuthorities;
	}

	public void setGroupAuthorities(Set<GroupAuthority> groupAuthorities) {
		this.groupAuthorities = groupAuthorities;
	}

}
